const oracledb = require('oracledb');

async function run() {
    let connection;

    try {
        // Update these details with your database connection info
        connection = await oracledb.getConnection({
            user: 'your_username',
            password: 'your_password',
            connectString: 'your_connect_string'
        });

        // Create a table
        const createTableQuery = `
            CREATE TABLE books (
                id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                title VARCHAR2(255),
                author VARCHAR2(255),
                PRIMARY KEY(id)
            )
        `;
        await connection.execute(createTableQuery);

        // Insert data
        const insertQuery = `INSERT INTO books (title, author) VALUES (:1, :2)`;
        await connection.executeMany(insertQuery, [
            ['The Great Gatsby', 'F. Scott Fitzgerald'],
            ['To Kill a Mockingbird', 'Harper Lee'],
            ['1984', 'George Orwell'],
            ['Pride and Prejudice', 'Jane Austen'],
            ['The Catcher in the Rye', 'J.D. Salinger']
        ]);

        // Commit the transaction
        await connection.commit();

        console.log('Table created and data inserted successfully');
    } catch (err) {
        console.error('Error occurred', err);
    } finally {
        if (connection) {
            try {
                await connection.close();
            } catch (err) {
                console.error('Error closing connection', err);
            }
        }
    }
}

run();

